# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Mr.Teal here
# Description of the Site
description: 
# URL of Image of the Site
site-image: /assets/images/Tony Montana aka Mr Teal.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://c0.wallpaperflare.com/preview/316/530/418/skyline-ocean-skyscraper-downtown.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: UltramanRuebe@outlook.com
github_username:  Mr-Teal

# Name of the Author
author-name: Mr.Teal
# URL for the Image of the Author
author-image: /assets/images/Tony Montana aka Mr Teal.jpg
# 60 Words About the Author
author-about: Ze rain, she is tres wet zis time of the year.
author-url: https://github.com/Mr-Teal

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
